### ISSUE TITLE
"Failed to connect with 'host::'" error.

### ISSUE THREAD

**Issue by beaufortfrancois** [webadb/webadb.js#1]
Steps to reproduce:
1. Go to https://webadb.github.io/
2. Plug my "Google Pixel" phone, make sure USB debugging is enabled
3. Click "I understand and accept" button
4. Click "Connect" button
5. Select the device in the USB chooser and click "Connect"

What happens?

I get "Failed to connect with 'host::'" error.
For info, the response I get in "connectAdb" is `Adb.Message {cmd: "AUTH", arg0: 1, arg1: 0, data: DataView(20)}`

**Comment by cavokz** [comment]
Please retry, I synchronized with my development branch, a lot changed.

**Comment by beaufortfrancois** [comment]
Thank you! I can now connect to it.
Is that expected I get "ls: /tmp/test_webadb.txt: No such file or directory" when I press the "Send" button?

**Comment by cavokz** [comment]
you can try with /sdcard/Download/test_webadb.txt

**Comment by beaufortfrancois** [comment]
Argh, I can't connect it succesfully to it now ;(

```
key is not extractable
```

From https://webadb.github.io/?debug=yes&dump=yes

**Comment by cavokz** [comment]
Which version of Chrome/Chromium are you using?

**Comment by beaufortfrancois** [comment]
```
Google Chrome	63.0.3230.0 (Official Build) canary (64-bit)
Revision	0
Platform	10009.0.0 (Official Build) canary-channel samus
Firmware Version	Google_Samus.6300.174.0
Customization ID	SAMUS
```

**Comment by cavokz** [comment]
Windows, right?

**Comment by beaufortfrancois** [comment]
Chrome OS

**Comment by cavokz** [comment]
Please try again.

**Comment by beaufortfrancois** [comment]
Yeah. It works now! Thank you ;)

**Comment by beaufortfrancois** [comment]
Sending `shell:ls -l /sdcard/Download/test_webadb.txt` though still doesn't work
I get "ls: /sdcard/Download/test_webadb.txt: No such file or directory" ;(

**Comment by beaufortfrancois** [comment]
Hitting "Push" button first helps ;)
You may want to move the "Push" button first so that user can simply clicks each button in the top order.

**Comment by cavokz** [comment]
ok, that's nice. it shows that the file is not there. now if you push it, it will show up.

**Comment by cavokz** [comment]
reordered actions so to minimize surprises for the user.

**Comment by cavokz** [comment]
Thank you too @beaufortfrancois!
