### ISSUE TITLE
License

### ISSUE THREAD

**Issue by pdjstone** [webadb/webadb.js#3]
Could you add a license for this project?

**Comment by cavokz** [comment]
I am a great fan of free software and, as idealistic choice, I would pick GPLv3. On the other hand, I'd like to serve also those users not having the option of adopting any GPL in their (evil) environment and, frankly, I am afraid of shooting on my foot with it.

I believe that voluntarily giving back even if the license does not require it might actually build a better community.

What licenses are mostly used in the web palaces? I need some advice here.

Thanks.

**Comment by pdjstone** [comment]
Lots of Javascript projects use MIT for simplicity. Speaking selfishly, an MIT/BSD type license would work better for me than GPL but it's obviously your choice. Take a look at https://choosealicense.com/ for a bit more info.

**Comment by cavokz** [comment]
Let There Be MIT

Thanks
