### ISSUE TITLE
Unable to claim interface.

### ISSUE THREAD

**Issue by Zibri** [webadb/webadb.js#7]
It used to work (last time I tried) now it doesn't.
I am running the latest version of chrome on linux.
But the phone(s) connects to webusb api with no problems..
![image](https://user-images.githubusercontent.com/855176/53785287-a5857100-3f20-11e9-8747-484940f3e87a.png)

**Comment by cavokz** [comment]
It is not obvious to me the context in which you get this error. Is it reproducible? How do you reproduce it?

**Comment by Zibri** [comment]
I just connected to: https://webadb.github.io/
The paired the phone.
And then I get that error.

**Comment by Zibri** [comment]
![image](https://user-images.githubusercontent.com/855176/55685085-a7dd4f80-5952-11e9-9f4f-9312fbb126eb.png)

**Comment by Zibri** [comment]
Nevermind I found out the problem.
I had adb running on the same pc.
Just add a note to issue adb kill-server before attempting the test :D

**Comment by rootmonty** [comment]
The solution mentioned by to kill adb server just before testing, is not working in my case. Also I am testing in incognito mode so there is no scope of caching as well. 
Can you help me out here?

**Comment by mebjas** [comment]
On killing local adb server, now I am getting another issue
```
NetworkError: A transfer error has occurred.
```

Any known reasons for this?

**Comment by cavokz** [comment]
> 
> 
> On killing local adb server, now I am getting another issue
> 
> ```
> NetworkError: A transfer error has occurred.
> ```
> 
> Any known reasons for this?

Do you have some more stack trace? I cannot guess where/when this error comes out.

**Comment by cavokz** [comment]
> 
> 
> The solution mentioned by to kill adb server just before testing, is not working in my case. Also I am testing in incognito mode so there is no scope of caching as well.
> Can you help me out here?

What OS are you using? Does Android's SDK adb works fine?

**Comment by veeragoni** [comment]
> The solution mentioned by to kill adb server just before testing, is not working in my case. Also I am testing in incognito mode so there is no scope of caching as well. Can you help me out here?

I had issue with adb running. after killing it I had issue connect as well. I had to disable and enable the USB debugging again so that I can authorize it once again. then it worked. its again, in the developer settings. simply disable developer settings, enable it and enable the usb debugging as well. most likely the USB debugging is disabled.

**Comment by cavokz** [comment]
> > The solution mentioned by to kill adb server just before testing, is not working in my case. Also I am testing in incognito mode so there is no scope of caching as well. Can you help me out here?
> 
> I had issue with adb running. after killing it I had issue connect as well. I had to disable and enable the USB debugging again so that I can authorize it once again. then it worked. its again, in the developer settings. simply disable developer settings, enable it and enable the usb debugging as well. most likely the USB debugging is disabled.

Thanks for letting us know :)
